name = "kiddo-adventures"
main = "src/index.js"
compatibility_date = "2026-08-15"
workers_dev = true
preview_urls = true

[assets]
directory = "../web/dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*"]

[[d1_databases]]
binding = "DB"
database_name = "kiddo-adventures-db"
database_id = "6c675a7d-ca96-4626-926d-4d239cbf08e3"
